import React, {Component} from 'react'

class Termino extends Component {
    render(){
        return(
            <div className="termino container-fluid">
                <section className="term-1-section container">
                    <h1 className="h6 font-weight-bold">Terminos y condiciones de uso del sitio web <a href="www.myibanwallet.com">www.myibanwallet.com</a></h1>

                    <h6>1. Información legal y aceptación</h6>
                    <p>Los términos y condiciones recogidos en el presente Aviso Legal regulan el uso del Sitio Web www.myibanwallet.com (en adelante, el "Sitio Web") que IBANWALLET pone a disposición de los Usuarios que accedan a su Sitio Web (en adelante, el “Usuario” o “Usuarios”) con la finalidad de proporcionarles información sobre sus servicios y sobre los productos ofertados correspondientes a terceras empresas del sector financiero y asegurador, así como posibilitar la contratación de dichos servicios y/o productos.</p>
                    <p>iBAN Investment Group S.L., con domicilio en Paseo de las delicias, 1, 41001, Sevilla, España, correo electrónico: hola@myibanwallet.com,  y con CIF  B-36470235. Si desea contactar con IBANWALLET puede utilizar la dirección de correo postal arriba indicada, o si lo prefiere a través del correo electrónico soportelegal@myibanwallet.com.</p>
                    <p>La utilización del Sitio Web por los Usuarios implica la aceptación de todas las condiciones incluidas en este Aviso Legal.</p>
                    <p>Los Usuarios deben leer atentamente el Aviso Legal presente en el Sitio Web en cada una de las ocasiones en que se propongan utilizar el mismo, ya que éste puede sufrir modificaciones sin previo aviso.</p>
                    <p>Algunos servicios del Sitio Web accesibles para los Usuarios están sometidos a condiciones generales de contratación, condiciones particulares, reglamentos e instrucciones que, en su caso, sustituyen, completan y/o modifican los presentes términos y condiciones, y que deberán ser aceptadas por los Usuarios antes de realizarse la prestación del servicio correspondiente.</p>
                    <p>El acceso a y/o la utilización de dichos servicios y contenidos expresa la entera e incondicional aceptación de las condiciones particulares en la versión publicada por IBANWALLET en el momento en que se produzca dicho acceso y/o utilización.</p>
                    <p>Es posible que, a lo largo de la prestación de los servicios incluidos en el Sitio Web, se modificase el nombre del dominio bajo el cual dichos servicios se prestan. Por lo tanto, los Usuarios conocen y aceptan esta posibilidad, permaneciendo en tal caso completamente vigente las obligaciones aceptadas por los Usuarios y IBANWALLET en función de lo establecido en este documento.</p>

                    <h6>2. Condiciones de uso de los contenidos y servicios</h6>
                    <p>El uso del Sitio Web y su contenido es totalmente voluntario y bajo la responsabilidad del Usuario.</p>
                    <p>El acceso al Sitio Web es gratuito salvo en lo relativo al coste de la conexión a través de la red de telecomunicaciones suministrada por el proveedor de acceso contratado por el Usuario.</p>
                    <p>Los Usuarios únicamente podrán acceder a los contenidos mediante los medios o procedimientos que se hayan puesto a su disposición a este efecto en el Sitio Web o se utilicen habitualmente en Internet para ese fin, siempre que no impliquen la violación de derechos de propiedad intelectual o industrial o impliquen algún tipo de daño para el Sitio Web y/o su información o servicios ofrecidos.</p>
                    <p>Los Usuarios se obligan a usar los contenidos y servicios de forma diligente, legal, correcta y lícita y, en particular, se comprometen a título meramente enunciativo y no exhaustivo a abstenerse de:</p>
                    <ul>
                        <li>Utilizar los contenidos y servicios de forma que produzcan o puedan producir efectos y/o con fines contrarios a la ley, a la moral y a las buenas costumbres generalmente aceptadas o al orden público.</li>
                        <li>Transmitir o difundir información, datos, contenidos, mensajes, gráficos, dibujos, archivos de sonido y/o imagen, fotografías, grabaciones, software, y en general, cualquier material obsceno, ofensivo, vulgar o que induzca actuaciones delictivas, denigratorias, difamatorias, infamantes, violentas o, en general, contrarias a la ley, a la moral y buenas costumbres generalmente aceptadas o al orden público.</li>
                        <li>Reproducir, copiar, o distribuir los contenidos, así como permitir el acceso del público a los mismos a través de cualquier modalidad de comunicación pública, o transformarlos o modificarlos, a menos que se cuente con la autorización del titular de los correspondientes derechos o ello resulte legalmente permitido.</li>
                        <li>Vulnerar derechos de propiedad intelectual o industrial pertenecientes a IBANWALLET o a terceros.</li>
                        <li>Utilizar los servicios y contenidos de manera que pueda suponer un perjuicio o sobrecarga para el funcionamiento del Sitio Web.</li>
                        <li>Realizar transacciones fraudulentas o que puedan facilitar conductas ilícitas o fraudulentas de cualquier tipo y emplear los contenidos y servicios y, en particular, la información de cualquier clase obtenida a través del Sitio Web con cualquier tipo de finalidad publicitaria y, en especial, para remitir publicidad, comunicaciones con fines de venta directa o con cualquier otra clase de finalidad comercial, mensajes no solicitados individualizados o dirigidos a una pluralidad de personas, así como de comercializar o divulgar de cualquier modo dicha información. Los Usuarios responderán por los daños y perjuicios de toda naturaleza que IBANWALLET pueda sufrir, directa o indirectamente, como consecuencia del incumplimiento de cualquiera de las obligaciones derivadas de este Aviso Legal o de la ley en relación con la utilización del Sitio Web.</li>
                    </ul>

                    <h6>3. Registro en la página web y contraseña</h6>
                    <p>La contratación de los Servicios prestados y productos ofertados a través del Sitio Web requiere el registro previo de los Usuarios, para lo que se solicitará la elección de una contraseña que permita la identificación personal del Usuario. En lo relativo a la solicitud y tratamiento de datos de carácter personal por parte de IBANWALLET, se estará a lo establecido en la Cláusula 9 de este Aviso Legal.</p>
                    <p>A través del registro, se adquiere un identificador de Usuario, que será la dirección de correo electrónico y contraseña elegidas, que habrá sido generada por el propio Usuario durante el proceso de registro. Dicha clave de acceso será personal e intransferible. Estos datos serán solicitados cada vez que el Usuario quiera acceder con el fin de utilizar los servicios del Sitio Web, por lo que servirán de procedimiento de identificación y autenticación en el sistema. La contraseña elegida por el Usuario será personal e intransferible, no estando permitida la cesión, ni siquiera temporal, a terceros. En tal sentido, los Usuarios se comprometen a hacer un uso diligente y a mantener en secreto la contraseña elegida para acceder al Sitio Web y/o a los servicios que ésta proporciona. En el supuesto de que los Usuarios conozcan o sospechen de la pérdida, robo o uso de su contraseña por terceros, deberán poner tal circunstancia en conocimiento de IBANWALLET a la mayor brevedad.</p>
                    <p>Se recomienda a los Usuarios modificar periódicamente la contraseña. El Usuario custodiará con la debida diligencia dicha contraseña y será responsable de cualquier uso o acceso a la misma por parte de terceros no autorizados. IBANWALLET no solicitará por ningún medio, ya sea correo electrónico, u otros, que el Cliente informe de la clave o contraseña que permitan el acceso a los servicios del Sitio Web por parte del Usuario. El Usuario se obliga a no comunicar a terceros la clave de acceso. Cada Usuario responderá de los gastos y de los daños y perjuicios ocasionados por la utilización de los servicios por cualquier tercero que emplee al efecto su contraseña gracias a una utilización no diligente o a la pérdida de los mismos por el Usuario.</p>
                    <p>Una vez registrado, el Usuario recibirá un código alfanumérico. Dicho código tendrá como objetivo verificar su identidad cuando éste quiera contratar uno de los servicios o productos ofertados a través del Sitio Web, para ello, siempre que quiera realizar dicha contratación se le solicitará que facilite dicho código.</p>

                    <h6>4. Solicitud de contratación</h6>
                    <p>Cuando un Usuario, previamente registrado, quiera solicitar un producto o servicio a través del Sitio Web, deberá cumplimentar un cuestionario a través del cual se le solicitarán una serie de datos personales al objeto de valorar el perfil de riesgo financiero del propio Usuario y poder recomendarle la mejor inversión mediante los productos y servicios que mejor se adecuen a sus necesidades y perfil financiero. Así, una vez cumplimentado el correspondiente cuestionario, se le ofrecerán los productos y servicios disponibles a través del Sitio Web en atención al nivel de riesgo vertido por las respuestas dadas por aquél.</p>
                    <p>En cualquier caso, si mostrado el perfil de riesgo financiero que se hubiera determinado en atención a las respuestas ofrecidas por el Usuario, éste no estuviera de acuerdo con el mismo, podrá seleccionar los productos correspondientes a un perfil de riesgo inferior al determinado por el propio Sitio Web.</p>
                    <p>En esta fase de solicitud de contratación, en lo relativo a la recogida y tratamiento de datos de carácter personal por parte de IBANWALLET, se estará nuevamente a lo establecido en la Cláusula 9 de este Aviso Legal.</p>

                    <h6>5. Exclusión de garantías y de responsabilidad</h6>
                    <p>IBANWALLET se reserva el derecho a interrumpir el acceso al Sitio Web, así como la prestación de cualquiera o de todos los contenidos que se prestan a través del mismo en cualquier momento y sin previo aviso, ya sea por motivos técnicos, de seguridad, de control, de mantenimiento, por fallos de suministro eléctrico o por cualquier otra causa fundada.</p>
                    <p>En consecuencia, IBANWALLET no garantiza la fiabilidad, la disponibilidad ni la continuidad del Sitio Web ni de los contenidos, por lo que la utilización de los mismos por parte de los Usuarios se lleva a cabo por su propia cuenta y riesgo, sin que, en ningún momento puedan exigirse responsabilidades por la discontinuidad o falta de disponibilidad de sus servicios.</p>
                    <p>IBANWALLET no será responsable en caso de que existan interrupciones del servicio, demoras, errores, mal funcionamiento del mismo y, en general, demás inconvenientes que tengan su origen en causas que escapan del control de IBANWALLET, y/o debidas a una actuación dolosa o culposa de los Usuarios y/o tengan por origen causas de Fuerza Mayor. Sin perjuicio de lo establecido en el artículo 1105 del Código Civil, se entenderán incluidos en el concepto de Fuerza Mayor, además, y a los efectos de las presentes condiciones generales, todos aquellos acontecimientos acaecidos fuera del control de IBANWALLET, tales como: fallo de terceros, operadores o compañías de servicios, actos de Gobierno, falta de acceso a redes de terceros, actos u omisiones de las Autoridades Públicas, aquellos otros producidos como consecuencia de fenómenos naturales, apagones, etc. y el ataque de hackers, crackers u otros terceros a la seguridad o integridad del sistema informático. En cualquier caso, sea cual fuere su causa, IBANWALLET no asumirá responsabilidad alguna ya sea por daños directos o indirectos, daño emergente y/o por lucro cesante.</p>
                    <p>IBANWALLET excluye cualquier responsabilidad por los daños y perjuicios de toda naturaleza que puedan deberse a la falta de veracidad, exactitud, exhaustividad y/o actualidad de los contenidos transmitidos, difundidos, almacenados, puestos a disposición o recibidos, obtenidos o a los que se haya accedido a través del Sitio Web, ni tampoco por los contenidos prestados u ofertados por terceras personas o entidades. IBANWALLET tratará en la medida de lo posible de actualizar y rectificar aquella información alojada en el Sitio Web que no cumpla con las mínimas garantías de veracidad. No obstante quedará exonerada de responsabilidad por su no actualización o rectificación así como por los contenidos e informaciones vertidos en la misma.</p>
                    <p>IBANWALLET no se responsabiliza por el contenido de la información recogida en el Sitio Web, así como por aquellas opiniones, comentarios, apreciaciones o cualquier otra manifestación recogida en el mismo que no sean emitidas directamente por IBANWALLET.</p>
                    <p>IBANWALLET excluye cualquier responsabilidad por los daños y perjuicios de toda clase que puedan deberse a la presencia de virus o a la presencia de otros elementos lesivos en los contenidos que puedan producir alteración en los sistemas informáticos, así como en los documentos o sistemas almacenados en los mismos.</p>
                    <p>IBANWALLET no se hace responsable de los contenidos, cualesquiera que sean los mismos, que los Usuarios envíen a IBANWALLET por medio del Sitio Web, por medio del servicio de correo electrónico o por cualquier otro medio, siendo por tanto imputable a los Usuarios cualquier responsabilidad dimanante de los contenidos enviados por los mismos.</p>

                    <h6>6. Enlaces web de terceros (enlaces salientes)</h6>
                    <p>La Compañía no asumirá ninguna responsabilidad en relación con enlaces web de terceros.</p>
                    <p>En el supuesto de que los Usuarios consideren que existe un enlace web de terceros con contenidos ilícitos o inadecuados podrán comunicárselo a IBANWALLET a la dirección de contacto señalada en el primer apartado de este Aviso Legal, indicando:</p>
                    <ul>
                        <li>Del comunicante: nombre, dirección, número de teléfono y dirección de correo electrónico.</li>
                        <li>Una descripción de los hechos que revelan el carácter ilícito o inadecuado del enace web de terceros. Una declaración expresa de que la información contenida en la comunicación es exacta.</li>
                    </ul>

                    <p>En ningún caso, la existencia de enlaces web de terceros debe presuponer la existencia de acuerdos con los responsables o titulares de los mismos, ni la recomendación, promoción o identificación de IBANWALLET con las manifestaciones, contenidos o servicios proveídos.</p>
                    <p>IBANWALLET no conoce los contenidos y servicios de los enlaces web de tercero y por tanto no se hace responsable por los daños producidos por la ilicitud, calidad, desactualización, indisponibilidad, error e inutilidad de los contenidos y/o servicios de los enlaces  web de terceros ni por cualquier otro daño que no sea directamente imputable a IBANWALLET.</p>
                    <p>Si los Usuarios deciden visitar y/o utilizar cualquiera los enlaces web de terceros, lo harán por su cuenta y riesgo, y tendrán que tomar las medidas de protección oportunas, en todo caso.</p>

                    <h6>7. Enlaces al sitio web (enlaces entrantes)</h6>
                    <p>No se autoriza a terceros a introducir enlaces desde sus propias páginas web al Sitio Web salvo consentimiento expreso de IBANWALLET.</p>
                    <p>En el caso de que se autorice a un tercero utilizar el enlace, este uso se hará respetando las limitaciones y finalidades previstas en la propia autorización.</p>
                    <p>IBANWALLET podrá solicitar, en cualquier momento y sin necesidad de aportar las razones de dicha solicitud, que se elimine cualquier enlace al Sitio Web, después de lo cual el responsable de la página web enlazante deberá proceder de inmediato a su eliminación.</p>

                    <h6>8. Propiedad intelectual e industrial</h6>
                    <p>La totalidad de los contenidos del Sitio Web, entendiendo por éstos a título meramente enunciativo los textos, fotografías, gráficos, imágenes, iconos, tecnología, software, links, dominios, marcas y demás contenidos audiovisuales o sonoros, así como su diseño gráfico y códigos fuente, son de la exclusiva propiedad de IBANWALLET o de terceros, cuyos derechos en su caso reconoce IBANWALLET, y están sujetos a derechos de propiedad intelectual e industrial protegidos por la legislación nacional e internacional.</p>
                    <p>Queda estrictamente prohibido cualquier utilización de cualquiera de los elementos objeto de propiedad industrial e intelectual con cualquier tipo de finalidad, en especial comercial, así como su distribución, comunicación pública, modificación, alteración, transformación o descompilación, salvo autorización expresa por escrito por parte del titular de los mismos.</p>
                    <p>La infracción de cualquiera de los citados derechos puede constituir una vulneración de las presentes disposiciones, así como una acción constitutiva de delito tipificada en los artículos 270 y siguientes del Código Penal.</p>

                    <h6>9. Política de privacidad y protección de datos de carácter personal</h6>
                    <p>Cualquier dato de carácter personal que los Usuarios faciliten durante el uso del Sitio Web será tratado conforme a nuestra Política de Privacidad presente en Política de Privacidad.</p>
                    <p>En los casos en los que el Usuario no haya mostrado su disconformidad a recibir información comercial, IBANWALLET podrá enviarle comunicaciones comerciales sobre sus servicios o novedades.</p>
                    <p>Los Usuarios deben leer y aceptar dicha Política de Privacidad antes de facilitar sus datos personales a IBANWALLET.</p>

                    <h6>10.Generalidades</h6>
                    <p>Cualquier cláusula o disposición del presente Aviso Legal que sea o devenga ilegal, inválida o inexigible será excluida del mismo y será considerada inaplicable en lo que alcance a tal ilegalidad, invalidez o inexigibilidad, y será sustituida por otra que se asemeje lo más posible a la anterior, pero no afectará o perjudicará a las restantes disposiciones, las cuales quedarán al margen de cualquier cláusula o disposición ilegal, inválida o inexigible y permanecerán por el contrario con plena vigencia y efecto.</p>
                    <p>IBANWALLET excluye cualquier tipo de garantía, y, por tanto, queda libre de total responsabilidad derivada de los puntos expresados con anterioridad, así como de otros aspectos que pueden no estar contemplados en el presente documento.</p>

                    <h6>11. Ley aplicable y jurisdicción</h6>
                    <p>La relación entre IBANWALLET y el Usuario se regirá por la normativa española vigente y cualquier controversia se someterá a los Juzgados y Tribunales del domicilio del Usuario.</p>

                </section>
            </div>
        )
    }


}

export default Termino